(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[167,92,158,69],[167,163,84,35],[0,92,165,88],[0,0,728,90],[0,182,70,22]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.fourteenbottomright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.fourteencookieleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.fourteencookietopright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.fourteentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.fourteentopleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.sweetinspiration = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AhABBQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQACgFgBgKIAAgJIAAgKIAAgNQAAgVgBgGQgBgGgCgCIgHgCQgIgDAAgEQAAgDACgCQADgDAGgCIATgGIAOgCQADAAACACQACACAAAEIAAAJIAAABIABAAIABAAIAAAAIADgDIADgCQAOgOAQAAQAJAAAJAEQAJAEAGAHQAGAIADAKQACAKAAAVIAAARIAAAJIAAAHQAAAJABAEQACAEADACIADACQAHACAAAEQAAAGgGACQgGACgVAAQgSAAgHgCQgFgCAAgFQgBgFAHgCIAFgCQADgCABgGQACgGAAgOQAAgpgGgLQgFgKgOAAQgHAAgGAEQgHAEgDAHQgDAGgBAKIgBAkQAAANABAEQABAEADACIAFACQAHACgBAFQABAFgHACQgGADgSAAQgTAAgHgDg");
	this.shape.setTransform(98,3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgvAyQgTgUAAgdQAAgdAUgUQATgUAdAAQAdAAASATQASASAAAdQAAAegTAUQgUAVgcAAQgcAAgTgTgAgYgnQgIALAAASQAAAZALASQALARAPAAQANAAAIgLQAIgKAAgSQAAgZgLgSQgMgRgOAAQgNAAgIAKg");
	this.shape_1.setTransform(82.7,3.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_2.setTransform(71.5,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgGBPQgHgCgFgEQgEgEgCgIQgCgHAAgUIAAhGIgMAAIgEgBIgBgDIAAgDQAAgFAOgLIAFgFIAFgEQAOgNAFAAIADACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAZIAdAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAAAEIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgbAAIgCACIgBADIAABAQAAARADAFQADAEAIAAQAEAAAGgCIAJgCQADAAACACQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAHgPAAQgHgBgGgCg");
	this.shape_3.setTransform(63.2,1.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgMAAgSQAAgVAPgLQAPgLAcgBQAGAAADACQAEACAAAFQAAAIgJgBQgNAAgIAHQgIAGAAALQAAALAHAGQAHAGAMAAQAMAAAFgFQAGgGAAgOIAAgxQAAgMgFgGQgFgGgJgBQgGAAgGADQgFADgGAGIgCAEQgIAKgJAAQgGAAgDgDQgDgEAAgFQAAgNAPgJQAQgIAYAAQAOAAAKAEQALAEAGAHQAEAFABAIQACAIAAATIAAAqQAAAHABAEQABADADACIAEABQAIACAAAFQAAAFgIAGQgJAFgMAAQgGAAgGgHg");
	this.shape_4.setTransform(51.6,3.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgnBBQgHgCAAgGQAAgEAHgCIADgCQAEgCABgEQABgFAAgKIAAgJIAAgKIAAgIQAAgYgBgHQgBgHgDgCIgGgCQgIgDAAgEQAAgDADgCQACgDAGgCIASgGIALgCQAHAAACASIAAACIABABQAGgLAIgFQAHgGAIAAQAJAAAFAGQAGAFAAAJQAAAKgEAFQgFAFgHAAIgHgBIgFgEIgDgFQgBgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgJAAgEANQgDANAAAnQAAALABAGQABAGAEACIAFABQAIADAAAFQAAAFgHACQgHADgSAAQgUAAgGgDg");
	this.shape_5.setTransform(39.6,3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_6.setTransform(30.4,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhABaQgGgCAAgGQAAgEAFgCIAHgEQADgCABgLQABgKAAghIAAgVQAAgkgCgKQgBgLgDgBIgGgDQgHgCgBgFQABgDACgCIAIgEIASgGQAJgDAEAAQAEAAACACQACACAAAFIAAAGIAAADIAAABIAGgEIAEgEQAIgGAIgDQAHgCAIAAQAYAAAQASQAQASAAAcQAAAfgSAUQgSAVgaAAQgMAAgEgDQgEgEAAgFQAAgDACgCQACgCAEAAIADABIAEAAQAPAAAJgMQAIgMABgUQgBgWgJgOQgJgOgQAAQgNAAgHAIQgIAHAAAUIAABTIAAAOQABAFACACIAHADIAGACIADACIAAAEQABAFgJACQgHACgTAAQgTAAgHgCg");
	this.shape_7.setTransform(18.6,5.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape_8.setTransform(5.3,3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhABBQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQACgFgBgKIAAgJIAAgKIAAgNQAAgVgBgGQgBgGgCgCIgHgCQgIgDAAgEQAAgDACgCQADgDAGgCIATgGIAOgCQADAAACACQACACAAAEIAAAJIAAABIABAAIABAAIAAAAIADgDIADgCQAOgOAQAAQAJAAAJAEQAJAEAGAHQAGAIADAKQACAKAAAVIAAARIAAAJIAAAHQAAAJABAEQACAEADACIADACQAHACAAAEQAAAGgGACQgGACgVAAQgSAAgHgCQgFgCAAgFQgBgFAHgCIAFgCQADgCABgGQACgGAAgOQAAgpgGgLQgFgKgOAAQgHAAgGAEQgHAEgDAHQgDAGgBAKIgBAkQAAANABAEQABAEADACIAFACQAHACgBAFQABAFgHACQgGADgSAAQgTAAgHgDg");
	this.shape_9.setTransform(-8.2,3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgbBdQgHgDgBgFQABgGAIgDIAGgCQACgCACgQIABg5IgBgyQgBgTgCgCQgBgDgHgCQgHgDgBgGQAAgFAHgCQAFgCAXAAQAYAAAGACQAFACABAFQAAAGgJADIgGADQgCACgBANIgBAsIABA+QABAXABACQACACAGADQAIACAAAGQAAAFgIADQgHACgVAAQgTAAgIgCg");
	this.shape_10.setTransform(-20.3,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgGBPQgHgCgFgEQgEgEgCgIQgCgHAAgUIAAhGIgMAAIgEgBIgBgDIAAgDQAAgFAOgLIAFgFIAFgEQAOgNAFAAIADACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAZIAdAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAAAEIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgbAAIgCACIgBADIAABAQAAARADAFQADAEAIAAQAEAAAGgCIAJgCQADAAACACQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAHgPAAQgHgBgGgCg");
	this.shape_11.setTransform(-36.4,1.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_12.setTransform(-48.1,3.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_13.setTransform(-62.1,3.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AAIAOIgQgoQgHgTgHgDIgDgCQgIgDAAgFQAAgFAHgCQAHgCAUAAQASAAAHACQAFACAAAFIAAAEIgDADIgEACQgFACgBADIADAJIAKAbIAMAZQADAGACAAQACAAACgEIAGgLIAOghQAFgNAAgEIgBgFIgDgDIgEgBQgGgDAAgEQAAgFAGgCQAGgCAQAAQAOAAAGACQAFACABAFQAAAFgIACIgEACQgGADgMAcIgDAGIgFAMQgfBEgIAAQgJAAgXg2gAhNAHIgDgHIgJgXQgJgWgGgDIgEgCQgHgDgBgFQAAgFAIgCQAGgCAWAAQARAAAHACQAGACAAAFIgBAEIgCADIgFACQgFACAAADIADALIAKAZIALAYQADAHACAAQAEAAAEgIIAEgKIADgEQACgBADAAQADAAACACQABACAAADQAAADgDAIQgOAegGAKQgGAKgFAAQgJAAgag9g");
	this.shape_14.setTransform(-79.7,3.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AggBfQgPgDgJgGQgFgDgEgLQgDgMAAgOQAAgGACgDQADgDAEgBQAGAAAHANIADAFQAIAOAKAIQAKAGAOAAQANAAALgIQAJgJAAgNQAAgSgmgSIgEgBQgggNgLgMQgKgMAAgSQAAgYARgQQASgPAcABIAPABIASADIAFgDIAFgBQADAAACACIAGAHQAEAJADAIQACAIAAAHQAAAEgCADQgCACgDAAQgHABgHgKIgCgDQgIgKgIgEQgJgEgLgBQgOABgJAGQgIAHAAAMQAAALAHAHQAHAHAcAMIAFACQAYAKAKAJQAHAHAEAJQAEAJAAAKQAAAbgTAQQgTAPggAAQgQAAgPgEg");
	this.shape_15.setTransform(-98.4,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sweetinspiration, new cjs.Rectangle(-108,-17.7,216.2,35.5), null);


(lib.partyreadyrecipesuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape.setTransform(119,3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQAAAAABABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_1.setTransform(106.4,3.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhABaQgGgCgBgGQABgEAFgCIAHgEQADgCABgLQABgKAAghIAAgVQAAgkgCgKQgBgLgCgBIgHgDQgHgCgBgFQAAgDACgCIAIgEIATgGQAJgDAFAAQADAAABACQADACAAAFIAAAGIAAADIAAABIAFgEIAGgEQAHgGAIgDQAHgCAHAAQAZAAAQASQAPASABAcQgBAfgRAUQgSAVgaAAQgMAAgDgDQgFgEAAgFQAAgDACgCQACgCAEAAIADABIAEAAQAPAAAJgMQAJgMAAgUQAAgWgKgOQgJgOgQAAQgNAAgHAIQgIAHAAAUIAABTIABAOQAAAFACACIAIADIAEACIAEACIABAEQAAAFgJACQgHACgTAAQgTAAgHgCg");
	this.shape_2.setTransform(91.3,5.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_3.setTransform(80,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgpAyQgTgUAAgcQAAgeAUgUQAUgUAdAAQAVAAAQALQAPAMAAAPQAAAGgEAEQgFAEgGAAQgHAAgEgDQgEgDgEgLQgFgKgFgDQgFgEgIAAQgOAAgJALQgJALABAVQAAAWALAPQANAPASAAQAGAAAHgCQAFgBAFgEIAGgEQAHgFAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQABABAAABQgBADgDAFQgCAEgFAEQgKAJgLAFQgMAEgNAAQgbAAgSgTg");
	this.shape_4.setTransform(69.6,3.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQAAAAABABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_5.setTransform(55.8,3.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AAdBCQgNgqgJgJQgJgIgNAAQgLAAAAgIQAAgIAJAAQAVAAALgIQAKgJAAgSQAAgSgKgIQgLgKgUABQgKgBgEACQgEABgBAEIgCAMIAAAbIAAA5IABAoQAAAJADACIAGACQAIADAAAGQAAAFgHADQgIACgVAAQgUAAgIgCQgHgDAAgFQAAgGAIgDIAGgCQADgCABgQIABg5IgBgyQgBgTgCgCQgBgDgHgDQgHgCAAgFQAAgFAEgDQAEgCAIAAIAdAAIAbAAIAUgBQAdAAAPAMQAQANAAAXQAAASgKANQgLAMgSAFIAAACQAOACAIAJQAIAIAHAWIADANQAFAVAIgBIAEAAIAFAAQAAAAABAAQABAAAAABQABAAAAAAQABABAAAAQACACAAADQAAAGgHAEQgIAEgMAAQgbAAgIgfg");
	this.shape_6.setTransform(39.6,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("Ag8BXQgHgFAAgIQAAgHAFgFQAFgFAGAAIAGABIAEADIAEAFQADAGADAAQAGAAAIgKQAGgKABgKQAAgMgKgVIgCgDIgVgtIgLgaQgDgFgHgDIAAAAQgGgCgBgCQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgGAGgCQAHgDAUAAQATAAAGACQAHACAAAGIAAAEIgDACIgFADQgFACAAACIADAKIALAaIAJAZQAEAGACAAQABAAADgGIAIgVIAKgaQAEgJAAgEQAAgDgIgFQgHgEAAgDQgBgFAHgCQAFgCAPAAQAQAAAGACQAFACAAAGQAAAFgHABIgFACQgIAEgIAXIgEAKIgRAqQgWA3gNAQQgOARgTAAQgKAAgGgGg");
	this.shape_7.setTransform(16.1,5.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("Ag5BQQgQgSAAgdQAAggASgTQASgUAcAAIAJABQAEABACADQACADAAADQAAAHgIAAIgDAAIgEAAQgPAAgIAMQgJALAAAVQAAAWAKAOQAJAOAPAAQANAAAIgIQAHgIAAgOIAAglIAAg8QAAgJgBgDQgCgEgFgCIgEgBQgIgCAAgFQAAgDADgDQAEgDAKgDIAOgEIANgCQAEAAACADQACACAAAGIAAAHIgCBQIABA4QABAMACACIAKADQAHACAAAEQAAAGgUAHIgNADIgKABQgEAAgBgCQgCgCAAgEIAAgHIAAgCIgBgBIgEADIgGAEQgIAGgGADQgIADgIAAQgZAAgPgSg");
	this.shape_8.setTransform(2,0.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgMAAgSQAAgVAPgLQAPgLAcgBQAGAAADACQAEACAAAFQAAAIgJgBQgNAAgIAHQgIAGAAALQAAALAHAGQAHAGAMAAQAMAAAFgFQAGgGAAgOIAAgxQAAgMgFgGQgFgGgJgBQgGAAgGADQgFADgGAGIgCAEQgIAKgJAAQgGAAgDgDQgDgEAAgFQAAgNAPgJQAQgIAYAAQAOAAAKAEQALAEAGAHQAEAFABAIQACAIAAATIAAAqQAAAHABAEQABADADACIAEABQAIACAAAFQAAAFgIAGQgJAFgMAAQgGAAgGgHg");
	this.shape_9.setTransform(-13.2,3.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_10.setTransform(-27.4,3.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAdBCQgNgqgJgJQgJgIgNAAQgLAAAAgIQAAgIAJAAQAVAAALgIQAKgJAAgSQAAgSgKgIQgLgKgUABQgKgBgEACQgEABgBAEIgCAMIAAAbIAAA5IABAoQAAAJADACIAGACQAIADAAAGQAAAFgHADQgIACgVAAQgUAAgIgCQgHgDAAgFQAAgGAIgDIAGgCQADgCABgQIABg5IgBgyQgBgTgCgCQgBgDgHgDQgHgCAAgFQAAgFAEgDQAEgCAIAAIAdAAIAbAAIAUgBQAdAAAPAMQAQANAAAXQAAASgKANQgLAMgSAFIAAACQAOACAIAJQAIAIAHAWIADANQAFAVAIgBIAEAAIAFAAQAAAAABAAQABAAAAABQABAAAAAAQABABAAAAQACACAAADQAAAGgHAEQgIAEgMAAQgbAAgIgfg");
	this.shape_11.setTransform(-43.6,0.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgZAOQgEAAgCgCQgCgBAAgEIABgGIADgHQACgEACgBQACgBAGAAIAGAAIALAAIAWgBIAEAAQAEAAACACQACABAAAEQAAAGgEAHQgEAGgHAAIgGAAIgHgBIgdACIgCAAg");
	this.shape_12.setTransform(-57.8,2.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("Ag8BXQgGgFgBgIQABgHAEgFQAFgFAHAAIAFABIAFADIADAFQADAGADAAQAHAAAGgKQAIgKgBgKQAAgMgJgVIgCgDIgUgtIgNgaQgCgFgIgDIAAAAQgEgCgCgCQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAAAQABgGAGgCQAIgDATAAQATAAAHACQAGACAAAGIAAAEIgDACIgFADQgFACAAACIACAKIAMAaIAKAZQADAGABAAQACAAADgGIAJgVIAJgaQADgJAAgEQABgDgIgFQgIgEABgDQAAgFAFgCQAHgCAPAAQAPAAAGACQAGACAAAGQAAAFgIABIgGACQgHAEgJAXIgDAKIgRAqQgWA3gNAQQgOARgTAAQgKAAgGgGg");
	this.shape_13.setTransform(-68.8,5.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgGBPQgHgCgFgEQgEgEgCgIQgCgHAAgUIAAhGIgMAAIgEgBIgBgDIAAgDQAAgFAOgLIAFgFIAFgEQAOgNAFAAIADACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAZIAdAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAAAEIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgbAAIgCACIgBADIAABAQAAARADAFQADAEAIAAQAEAAAGgCIAJgCQADAAACACQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAHgPAAQgHgBgGgCg");
	this.shape_14.setTransform(-80.1,1.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgnBBQgHgCAAgGQAAgEAHgCIADgCQAEgCABgEQABgFAAgKIAAgJIAAgKIAAgIQAAgYgBgHQgBgHgDgCIgGgCQgIgDAAgEQAAgDADgCQACgDAGgCIASgGIALgCQAHAAACASIAAACIABABQAGgLAIgFQAHgGAIAAQAJAAAFAGQAGAFAAAJQAAAKgEAFQgFAFgHAAIgHgBIgFgEIgDgFQgBgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgJAAgEANQgDANAAAnQAAALABAGQABAGAEACIAFABQAIADAAAFQAAAFgHACQgHADgSAAQgUAAgGgDg");
	this.shape_15.setTransform(-89.6,3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgMAAgSQAAgVAPgLQAPgLAcgBQAGAAADACQAEACAAAFQAAAIgJgBQgNAAgIAHQgIAGAAALQAAALAHAGQAHAGAMAAQAMAAAFgFQAGgGAAgOIAAgxQAAgMgFgGQgFgGgJgBQgGAAgGADQgFADgGAGIgCAEQgIAKgJAAQgGAAgDgDQgDgEAAgFQAAgNAPgJQAQgIAYAAQAOAAAKAEQALAEAGAHQAEAFABAIQACAIAAATIAAAqQAAAHABAEQABADADACIAEABQAIACAAAFQAAAFgIAGQgJAFgMAAQgGAAgGgHg");
	this.shape_16.setTransform(-101.9,3.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AhEBeQgHgDAAgFQAAgGAIgDIAGgDQACgCACgQIABg4IgBgyQgBgTgCgDQgCgCgGgDQgIgCABgFQAAgFAEgDQAEgCAIAAIAOAAIAPAAIAbAAIAUgBQAdAAAPANQAPAMABAZQAAAcgTAPQgSANgjAAQgNAAAAgJQAAgIALAAQAQAAALgJQAKgJAAgTQAAgSgKgJQgLgJgVAAQgKAAgDACQgEABgCAEIgBAMIAAAcIAAA5IABAmQAAAKACABIAHADQAHADABAGQAAAFgIADQgHACgVAAQgUAAgIgCg");
	this.shape_17.setTransform(-116.6,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipesuse, new cjs.Rectangle(-126.9,-17.7,254,35.5), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(42.7,19.4,0.328,0.328);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(20.4,9.9,0.328,0.328);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(26.6,29,0.328,0.328);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(17.2,28.9,0.328,0.328);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(7.4,28.9,0.328,0.328);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-3.6,29,0.328,0.328);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-14.5,28.9,0.328,0.328);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-25.6,29,0.328,0.328);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(4.8,-17.8,0.328,0.328);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-6.9,9.9,0.328,0.328);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-32.2,9.9,0.328,0.328);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(36.1,9.9,0.328,0.328);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-24.4,-12,0.328,0.328);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(22.7,-12.2,0.328,0.328);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(37.5,-12.2,0.328,0.328);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");
	this.shape_15.setTransform(0,0,0.328,0.328);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalelogo, new cjs.Rectangle(-57.3,-57.3,114.7,114.7), null);


(lib.holidaytipsrecipes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgkAqQgPgQgBgYQAAgZARgRQAQgRAZAAQAWAAAMAMQANAMAAAVQAAAHgCACQgCADgIAAIgrAAQgEAAgCgCQgBgCAAgDQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQACgBAEAAIAWAAIAGgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgLgIgIQgHgHgKAAQgNAAgGAMQgHALAAARQABAQAIANQAKANAMAAQAJAAAGgCQAFgCAGgEIADgDQAHgEACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgLAAQgWAAgRgQg");
	this.shape.setTransform(146.8,2.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AghA3QgGgBABgFQgBgEAGgCIADgBQACgCACgEIABgMIAAgHIAAgJIAAgHQAAgUgBgGQgBgGgCgCIgGgBQgGgDAAgDQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAHgEIAPgFIAKgCQAFAAACAPIAAADIAAAAQAGgJAGgFQAHgEAGAAQAIAAAEAEQAFAFAAAIQAAAIgEAEQgDAFgHAAIgFgBIgFgEIgCgEQgBgBAAgBQAAAAAAgBQgBAAAAAAQAAAAAAAAQgIAAgEALQgCAKAAAhQAAAKABAFQABAFADABIAEACQAIACAAAEQgBAFgGABQgGACgOAAQgRAAgGgCg");
	this.shape_1.setTransform(136.9,2.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgoAqQgQgRAAgZQAAgYARgRQARgQAYAAQAYAAAQAPQAPAQAAAZQAAAZgRARQgQARgYAAQgYAAgQgQgAgUggQgHAJAAAPQAAAVAJAPQAKAPAMAAQALAAAHgKQAHgJAAgPQAAgVgKgPQgJgPgNAAQgLAAgGAKg");
	this.shape_2.setTransform(126,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AApBPQgFgCAAgFQgBgEAIgDIAEgDQADgBAAgFIABgUIAAgGIgBgvIAAgcIgOAlQggBVgIAAQgDAAgHgMQgGgLgPglIgZg3IgBArIAAAeIAAAVQABAFACABIAFADQAGACABAFQAAAFgGACQgGACgNAAQgMAAgGgCQgFgCgBgFQAAgEAHgDQAFgDABgCQABgFACgdQACgcAAgjIAAgEIgBgQQgBgEgCgBIgGgDQgHgCAAgFQAAgEAFgCQAFgCAQAAIAQABIAEABQADABAIAUIAGAQIAEAIQAbBCABAAQADAAAJgYQAKgXAOgnIACgHQAFgMADgEQACgCAEgBIAPgBQAQAAAFACQAEACAAAEQAAAFgGACIgDABQgEACAAAFQgBAEAAARIABA/QABAdABAEQAAADAGABIACABIAEADQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAQABAFgHACQgGACgTAAQgQAAgHgCg");
	this.shape_3.setTransform(109.7,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhCBEQgWgQAAgaQABgPAGgLQAHgKAPgKIAAgBQgFgFgCgFQgCgGAAgGQAAgRAMgLQANgMAVAAQANAAAJAGQAJAFAAAHQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgCACgDAAIgJgDQgHgDgHAAQgJAAgGAGQgEAGAAAKIABAHQABAEADACQACADAGACIAHADIABAAIABACQABADgFAEQgEAFgDAAIgGgBIgHgDQgGAFgEAIQgDAIAAAKQAAAVAOAOQAOAOAWAAQARAAAMgKQALgJgBgPQAAgKgEgFQgEgGgJAAQgHAAgFAFQgFAEAAAHIAAADIAAABIgBAAIgBAAQgEAAgDgDQgDgDABgFQgBgQAxgXIADgBQANgGAHgHQAHgHAAgIQAAgFgEgDQgCgCgGAAIgEAAIgFABQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgFAGgDQAGgDAKAAQAMAAAHAGQAGAHAAALQABAOgMAMQgMALgZAJQAKAEAFAIQAGAJAAALQAAAIgDAIQgEAJgGAGQgLALgOAGQgQAGgTAAQgiAAgUgQg");
	this.shape_4.setTransform(84.4,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgIA6IgLgCIgEACIgDABIgDgBIgCgBQgEgDgDgJQgDgJAAgJQAAgDACgDQACgCADAAQAFAAAFAJIAEAHQAEAEAFADQAGACAGAAQAHAAAFgDQAEgEAAgGQAAgKgSgJIgGgDQgSgJgGgGQgGgHAAgLQAAgOAKgKQAKgJAQAAIAHABIAIABIAGgCIADgBQAGAAAFAJQAFAJAAAKQAAAEgCACQgBACgEAAQgCAAgDgCIgGgIQgEgHgEgCQgFgDgGAAQgGAAgEAEQgEADAAAGQAAAFAFAEQAEAEANAHIABABQAfAOAAASQAAAQgMAKQgMALgSAAg");
	this.shape_5.setTransform(63.3,2.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgkAqQgPgQAAgYQAAgZAQgRQAQgRAZAAQAWAAAMAMQAMAMAAAVQAAAHgCACQgBADgIAAIgrAAQgEAAgBgCQgDgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABgBQABgBAEAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQgBgLgGgIQgIgHgKAAQgMAAgHAMQgGALAAARQgBAQAKANQAJANAMAAQAJAAAFgCQAGgCAFgEIAFgDQAFgEAEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgDAEIgHAHQgKAIgJAEQgJADgKAAQgXAAgRgQg");
	this.shape_6.setTransform(52.7,2.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("Ag1BNQgGgDAAgEQAAgEAFgCIAFgCQADgDABgJIAAgkIAAgSQAAgegBgJQgBgJgCgCIgFgBQgHgDAAgDQAAgDACgCIAGgEIAQgEIAMgDQAAAAABABQABAAAAAAQABAAAAABQABAAAAABIABAFIAAAGIABABIAAABIAFgCIAEgEQAHgFAFgCQAHgDAGAAQAVAAANAPQANAQAAAXQAAAbgOARQgPARgXAAQgKAAgDgDQgDgCAAgFIABgEQACgCADAAIADABIAEAAQAMAAAHgKQAIgLAAgQQAAgTgIgMQgIgLgNAAQgLgBgHAHQgGAGAAARIAABHIAAALQABAEABACIAHADIAEABIADADIAAADQAAADgGADQgHABgQAAQgQAAgFgBg");
	this.shape_7.setTransform(39.8,4.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgTBQQgGgCAAgFQAAgEAGgCIADgBQADgBABgEQABgEAAgIIAAgIIAAgJIAAgMIgBgWQgBgFgCgBIgFgCQgHgCAAgEQAAgCACgCIAHgEIARgGIALgCQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAIABAIIAAAGIAAAFIgBAcIAAABIAAAbIABAPQABAFACABIAEACQAGACAAAEQAAAEgFACQgGACgOAAQgQAAgGgCgAgNg3QgFgEAAgGQAAgHAGgEQAFgFAHAAQAHAAAFAFQAEAEAAAGQAAAGgFAEQgFAEgHAAQgHAAgFgDg");
	this.shape_8.setTransform(30.3,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgjAqQgPgQAAgYQgBgZASgRQAQgRAYAAQATAAANAJQANAKgBANQAAAFgDADQgDAEgGAAQgGAAgDgDQgEgDgDgJQgEgIgFgDQgEgDgGAAQgMAAgIAJQgHAKAAARQAAATAKANQALAMAPAAQAFAAAFgBQAFgCAFgDIADgDQAHgFADAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABIABADQAAADgCAEIgGAHQgJAIgKAEQgJADgLAAQgXAAgQgQg");
	this.shape_9.setTransform(21.5,2.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgkAqQgPgQAAgYQAAgZAQgRQARgRAYAAQAVAAANAMQAMAMAAAVQAAAHgCACQgCADgHAAIgrAAQgDAAgDgCQgCgCAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQADgBADAAIAXAAIAFgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgLgGgIQgIgHgKAAQgNAAgGAMQgGALAAARQgBAQAKANQAIANANAAQAJAAAGgCQAFgCAFgEIAFgDQAFgEAEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgCAEIgIAHQgKAIgJAEQgJADgKAAQgXAAgRgQg");
	this.shape_10.setTransform(9.8,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAYA4QgKgkgIgHQgHgHgMAAQgJAAAAgHQAAgGAIgBQASAAAJgHQAIgHAAgPQAAgPgJgIQgJgHgQAAIgMABQgEABgBADIgBAKIAAAXIAAAwIAAAiQABAIACABIAFACQAHADAAAFQAAAFgGACQgGABgSAAQgRAAgHgBQgGgCAAgFQAAgEAHgEIAFgCQACgCABgNIABgvIgBgrQgBgQgBgCQgBgCgGgCQgGgCAAgFQAAgEADgCQAEgCAHAAIAYAAIAXgBIARAAQAYAAANAKQANALAAAUQAAAOgIALQgJALgPAEIAAABQAMACAGAIQAHAHAGASIADALQAEASAGAAIAEgBIAEAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAGgGADQgHADgKAAQgWAAgIgag");
	this.shape_11.setTransform(-3.8,0.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgLAiQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIACgFIACgDIAHgMIACgIIgBgEIgEgBQgFgCgDgEQgDgEAAgGQAAgIAFgEQAEgFAHAAQAHAAAFAGQAFAHAAAKQAAAHgDAIQgDAIgHAMIgFAIIgFADIgFgBg");
	this.shape_12.setTransform(-21.1,8.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgIA6IgLgCIgEACIgDABIgDgBIgCgBQgEgDgDgJQgDgJAAgJQAAgDACgDQACgCADAAQAFAAAFAJIAEAHQAEAEAFADQAGACAGAAQAHAAAFgDQAEgEAAgGQAAgKgSgJIgGgDQgSgJgGgGQgGgHAAgLQAAgOAKgKQAKgJAQAAIAHABIAIABIAGgCIADgBQAGAAAFAJQAFAJAAAKQAAAEgCACQgBACgEAAQgCAAgDgCIgGgIQgEgHgEgCQgFgDgGAAQgGAAgEAEQgEADAAAGQAAAFAFAEQAEAEANAHIABABQAfAOAAASQAAAQgMAKQgMALgSAAg");
	this.shape_13.setTransform(-29.4,2.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("Ag1BNQgGgDAAgEQAAgEAFgCIAFgCQADgDABgJIAAgkIAAgSQAAgegBgJQgBgJgCgCIgFgBQgHgDAAgDQAAgDACgCIAGgEIAQgEIAMgDQAAAAABABQABAAAAAAQABAAAAABQABAAAAABIABAFIAAAGIABABIAAABIAFgCIAEgEQAHgFAFgCQAHgDAGAAQAVAAANAPQANAQAAAXQAAAbgOARQgPARgXAAQgKAAgDgDQgDgCAAgFIABgEQACgCADAAIADABIAEAAQAMAAAHgKQAIgLAAgQQAAgTgIgMQgIgLgNAAQgLgBgHAHQgGAGAAARIAABHIAAALQABAEABACIAHADIAEABIADADIAAADQAAADgGADQgHABgQAAQgQAAgFgBg");
	this.shape_14.setTransform(-41.1,4.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgTBQQgGgCAAgFQAAgEAGgCIADgBQADgBABgEQABgEAAgIIAAgIIAAgJIAAgMIgBgWQgBgFgCgBIgFgCQgHgCAAgEQAAgCACgCIAHgEIARgGIALgCQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAIABAIIAAAGIAAAFIgBAcIAAABIAAAbIABAPQABAFACABIAEACQAGACAAAEQAAAEgFACQgGACgOAAQgQAAgGgCgAgNg3QgFgEAAgGQAAgHAGgEQAFgFAHAAQAHAAAFAFQAEAEAAAGQAAAGgFAEQgFAEgHAAQgHAAgFgDg");
	this.shape_15.setTransform(-50.6,0);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgWBQQgHgCAAgFQAAgFAGgCQAGgCABgCQABgCABgSIABg0IAAgeIgBgSQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAIgGgBIgFAAQgIAAgEACQgEACgDAFIgEAHIgEAIIgCADIgFABQgDAAgBgCQgCgDAAgHQAAgPADgKQAEgJAFAAIABAAQAKACANAAIBBAAQAOAAAIgCIACAAQAFAAAEAJQADAKAAAPQAAAGgBADQgCADgEAAIgDgBIgEgDIgDgIIgDgHQgEgFgEgCQgEgCgIAAIgFAAIgGABQgCABgBAEIAAARIgBAeIABA0QAAASACACQABACAGACQAGACAAAFQAAAFgGACQgHABgRAAQgRAAgFgBg");
	this.shape_16.setTransform(-60.9,0.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgzBKQgFgFAAgHQAAgFAEgEQAEgEAFAAIAFAAIAEADIADAEQADAEACAAQAFAAAGgIQAGgIAAgJQAAgJgIgSIgBgDIgSgmIgKgWQgCgEgHgDQgEgBgBgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgFAGgCQAGgCAQAAQAQAAAGACQAFACAAAFIAAADIgCACIgFACQgEACAAACIACAIIAJAWIAJAVQADAGABAAQABAAADgGIAHgRIAJgWIACgLQAAgDgGgEQgGgDAAgDQAAgEAFgCQAFgCAMAAQAOAAAFACQAEACAAAFQAAAEgGABIgFACQgGADgHATIgDAJIgPAjQgSAugLAPQgMAOgQAAQgIAAgGgFg");
	this.shape_17.setTransform(-79.9,4.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AAUA0IgGgFIgFACQgNAKgOAAQgQAAgKgKQgKgJAAgQQAAgSANgJQANgKAXAAQAFAAADACQADABAAAFQAAAFgIAAQgKAAgHAFQgHAGAAAKQAAAIAGAFQAGAGAKAAQAKAAAEgFQAFgFAAgMIAAgpQAAgKgEgFQgFgGgHAAQgFAAgFADQgFACgEAGIgCADQgHAIgIAAQgEAAgDgDQgCgDAAgEQAAgLANgHQANgIAUABQALAAAJADQAJADAFAGQAEAEABAIQABAGAAAQIAAAjIABAKQABABAAAAQAAABABAAQAAABABAAQAAAAABABIADABQAHACAAADQAAAGgHAEQgIAEgKABQgFAAgFgHg");
	this.shape_18.setTransform(-91.4,2.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AgwBEQgNgPAAgZQAAgbAPgQQAPgRAYAAIAHABQAEABABACQACADAAACQAAAGgHAAIgDAAIgCAAQgNAAgHAKQgIAJAAASQAAATAIAMQAIALANAAQALAAAGgGQAHgHAAgMIAAgfIAAgyQAAgIgCgDQgBgDgEgCIgDgBQgHgCAAgEQAAgDADgCQACgCAJgDIAMgEIALgBQAEAAABACQACACAAAFIAAAGIgCBEIABAvQABALACABIAIADQAFABAAAEQAAAFgQAGIgLACIgIABQgBAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgCAAgEIAAgFIgBgCIAAgBIgEACIgFAEQgGAFgGACQgGADgHAAQgVAAgNgPg");
	this.shape_19.setTransform(-103.7,0.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AgTBQQgGgCAAgFQAAgEAGgCIADgBQADgBABgEQABgEAAgIIAAgIIAAgJIAAgMIgBgWQgBgFgCgBIgFgCQgHgCAAgEQAAgCACgCIAHgEIARgGIALgCQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIABAIIAAAGIAAAFIgBAcIAAABIAAAbIABAPQABAFACABIAEACQAGACAAAEQAAAEgFACQgGACgOAAQgQAAgGgCgAgNg3QgFgEAAgGQAAgHAGgEQAFgFAHAAQAHAAAFAFQAEAEAAAGQAAAGgFAEQgFAEgHAAQgHAAgFgDg");
	this.shape_20.setTransform(-114,0);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AgSBQQgGgBAAgFQAAgEAFgCIAGgDQACgCAAgGIABgXIAAgRIAAgUIAAgJQAAgcgBgIQgBgIgCgCIgHgCQgHgCAAgEQAAgDACgCQACgCAIgCIAPgEIALgCQADAAABACQACACAAAFIAAAJQgCAoAAAoIABAmQABAIACACIAGADQAFACAAAEQAAAFgGACQgFABgPAAQgQAAgFgCg");
	this.shape_21.setTransform(-120.4,0);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AgoAqQgQgRAAgZQAAgYARgRQARgQAYAAQAYAAAQAPQAPAQAAAZQAAAZgRARQgQARgYAAQgYAAgQgQgAgUggQgHAJAAAPQAAAVAJAPQAKAPAMAAQALAAAHgKQAHgJAAgPQAAgVgKgPQgJgPgNAAQgLAAgGAKg");
	this.shape_22.setTransform(-129.6,2.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AAZBPQgHgCABgFQAAgFAGgCIAGgDQACgBAAgHIABgaIAAgQIgBgEQgBgCgFgBQgGgBgVAAIgXAAQgGABgCACIgBADIgBAIIAAAKIABAaQAAAHACABIAGADQAGACAAAFQAAAFgGACQgGACgSAAQgRAAgGgCQgHgCAAgFQAAgEAHgDIAFgDQACgBACgPIABguIgBgqQgCgRgBgCQgBgCgGgCQgGgCAAgFQAAgEAFgCQAFgCAUAAQAUAAAFACQAFACAAAEQAAAFgGACIgGADQgCABAAAHIgBAhQAAAFAEABQAEACARAAIAIAAIAXgBQAIgBABgBIACgCIAAgFIAAgFIgBgbQAAgGgCgBIgGgDQgGgCAAgFQgBgEAGgCQAFgCAUAAQAUAAAFACQAFACAAAEQAAAFgHACIgFADQgDABAAAQIgBAtIABAqQAAARACACQABACAGACQAGADAAAEQAAAFgGACQgHACgRAAQgSAAgGgCg");
	this.shape_23.setTransform(-144.3,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaytipsrecipes, new cjs.Rectangle(-154.8,-15.3,309.7,30.6), null);


(lib.holidayhosting = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape.setTransform(120,3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhABaQgGgCAAgGQAAgEAFgCIAHgEQADgCABgLQABgKAAghIAAgVQAAgkgCgKQgBgLgCgBIgHgDQgHgCgBgFQAAgDADgCIAHgEIATgGQAJgDAEAAQAEAAACACQACACAAAFIAAAGIAAADIAAABIAFgEIAFgEQAJgGAHgDQAHgCAHAAQAZAAAQASQAQASAAAcQAAAfgSAUQgSAVgaAAQgMAAgDgDQgFgEAAgFQAAgDACgCQACgCAEAAIADABIAEAAQAPAAAJgMQAJgMAAgUQAAgWgKgOQgJgOgQAAQgNAAgHAIQgIAHAAAUIAABTIABAOQAAAFACACIAHADIAGACIADACIABAEQAAAFgJACQgHACgTAAQgTAAgHgCg");
	this.shape_1.setTransform(106.2,5.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_2.setTransform(94.9,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgbBeQgHgDAAgFQAAgGAHgCQAHgDACgCQABgCABgWIAAg+IAAgjIgBgUQgBgEgCgCIgHgBIgHAAQgIAAgGACQgFADgDAFIgFAJIgDAJIgEAEIgFACQgEgBgCgDQgBgDAAgJQgBgRAFgLQAEgLAGABIACAAQAKACAQgBIBNAAQAQABAKgCIACAAQAGgBAEALQAFALAAARQgBAJgBADQgCADgEABIgEgCIgFgEIgDgJIgFgJQgDgFgGgDQgFgCgIAAIgGAAIgIABQgCACAAAEIgBAUIgBAjIABA+QAAAWACACQABACAHADQAIACAAAGQAAAFgIADQgHACgVAAQgTAAgIgCg");
	this.shape_3.setTransform(82.7,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgwBWQgRgKAAgPQAAgGADgFQAEgEAHAAQAGAAADADQADAEACAGQACAKAJAFQAIAGARgBQAQABAMgIQALgHAAgJQAAgHgDgDQgFgDgJgBIgOABIgUACQgYAAgNgIQgMgIAAgLQAAgHAFgGQAEgFAJgGQgHgGgEgJQgEgJAAgKQAAgVAQgPQAQgOAaAAIAMABIAVAEQAEAAAHgCQAGgDAHgFIAFADIABAFQAAAGgEAFQgEAFgIAEIAFAKIABALQgBAXgPANQgQANgaAAIgNgBIgNgCIgEAFIgBAEQAAAGAFADQAHAEANAAIAUgCIAUgCQASAAAKAIQAKAHAAAPQAAAUgVAPQgUAOgggBQgZABgQgLgAgVhBQgHAIAAANQAAAOAHAJQAGAHALABQALgBAHgHQAHgJAAgNQAAgOgHgIQgHgJgKAAQgLAAgHAJg");
	this.shape_4.setTransform(60.4,5.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhABBQgHgCAAgGQAAgEAHgCIADgCQAEgCABgEQABgFABgKIgBgJIAAgKIAAgNQAAgVgBgGQgBgGgDgCIgGgCQgIgDAAgEQAAgDADgCQACgDAGgCIATgGIANgCQAEAAACACQACACgBAEIAAAJIABABIAAAAIABAAIABAAIADgDIACgCQAPgOAQAAQAJAAAJAEQAJAEAGAHQAGAIACAKQADAKAAAVIAAARIAAAJIAAAHQAAAJACAEQAAAEAEACIAEACQAGACAAAEQAAAGgGACQgGACgUAAQgTAAgGgCQgHgCAAgFQABgFAGgCIAFgCQADgCABgGQACgGgBgOQAAgpgFgLQgFgKgPAAQgFAAgHAEQgGAEgDAHQgDAGgCAKIgBAkQAAANABAEQABAEADACIAFACQAGACAAAFQAAAFgGACQgGADgRAAQgUAAgHgDg");
	this.shape_5.setTransform(45,3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_6.setTransform(33.3,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgGBPQgHgCgFgEQgEgEgCgIQgCgHAAgUIAAhGIgMAAIgEgBIgBgDIAAgDQAAgFAOgLIAFgFIAFgEQAOgNAFAAIADACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAZIAdAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAABAAAAIAAAEIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgbAAIgCACIgBADIAABAQAAARADAFQADAEAIAAQAEAAAGgCIAJgCQADAAACACQABAAAAAAQAAABABAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAHgPAAQgHgBgGgCg");
	this.shape_7.setTransform(25,1.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape_8.setTransform(14.5,3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgvAyQgTgUAAgdQAAgdAUgUQATgUAdAAQAdAAASATQASASAAAdQAAAegTAUQgUAVgcAAQgcAAgTgTgAgYgnQgIALAAASQAAAZALASQALARAPAAQANAAAIgLQAIgKAAgSQAAgZgLgSQgMgRgOAAQgNAAgIAKg");
	this.shape_9.setTransform(1.4,3.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAdBdQgHgDAAgFQAAgGAJgDIAFgCQADgCABgIIAAggIAAgSIgBgFQgBgDgHgBQgGgBgZAAIgbABQgIABgCACIgBAEIgBAJIAAALIABAgQABAIACACIAGACQAIADAAAGQAAAFgHADQgIACgVAAQgUAAgIgCQgHgDAAgFQAAgGAIgDIAGgCQADgCABgRIABg4IgBgxQgBgUgCgCQgBgDgHgCQgHgDAAgGQAAgFAGgCQAGgCAYAAQAXAAAGACQAGACAAAFQAAAGgIADIgGADQgCACgBAIIgBAnQAAAFAFACQAFACATAAIAKAAIAcAAQAIgBADgDIABgCIAAgFIAAgGIAAghQgBgGgDgCIgFgDQgJgDAAgGQAAgFAGgCQAHgCAXAAQAYAAAFACQAGACAAAFQAAAGgIADIgGADQgDACgBASQgBARAAAkIABAyQABAVACACQABACAHADQAHACAAAGQAAAFgHADQgIACgUAAQgVAAgIgCg");
	this.shape_10.setTransform(-16,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("Ag8BXQgHgFAAgIQAAgHAFgFQAFgFAGAAIAGABIAEADIAEAFQADAGADAAQAGAAAIgKQAGgKABgKQAAgMgKgVIgCgDIgVgtIgLgaQgDgFgHgDIAAAAQgGgCgBgCQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgGAGgCQAHgDAUAAQATAAAGACQAHACAAAGIAAAEIgDACIgFADQgFACAAACIADAKIAKAaIAKAZQAEAGACAAQABAAADgGIAIgVIAKgaQAEgJAAgEQAAgDgIgFQgHgEgBgDQAAgFAHgCQAFgCAPAAQAQAAAGACQAFACAAAGQAAAFgHABIgFACQgIAEgIAXIgEAKIgRAqQgWA3gNAQQgOARgTAAQgKAAgGgGg");
	this.shape_11.setTransform(-39.7,5.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgMAAgSQAAgVAPgLQAPgLAcgBQAGAAADACQAEACAAAFQAAAIgJgBQgNAAgIAHQgIAGAAALQAAALAHAGQAHAGAMAAQAMAAAFgFQAGgGAAgOIAAgxQAAgMgFgGQgFgGgJgBQgGAAgGADQgFADgGAGIgCAEQgIAKgJAAQgGAAgDgDQgDgEAAgFQAAgNAPgJQAQgIAYAAQAOAAAKAEQALAEAGAHQAEAFABAIQACAIAAATIAAAqQAAAHABAEQABADADACIAEABQAIACAAAFQAAAFgIAGQgJAFgMAAQgGAAgGgHg");
	this.shape_12.setTransform(-53.3,3.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("Ag5BQQgQgSAAgdQAAggASgTQASgUAcAAIAJABQAEABACADQACADAAADQAAAHgIAAIgDAAIgEAAQgPAAgIAMQgJALAAAVQAAAWAKAOQAJAOAPAAQANAAAIgIQAHgIAAgOIAAglIAAg8QAAgJgBgDQgCgEgFgCIgEgBQgIgCAAgFQAAgDADgDQAEgDAKgDIAOgEIANgCQAEAAACADQACACAAAGIAAAHIgCBQIABA4QABAMACACIAKADQAHACAAAEQAAAGgUAHIgNADIgKABQgEAAgBgCQgCgCAAgEIAAgHIAAgCIgBgBIgEADIgGAEQgIAGgGADQgIADgIAAQgZAAgPgSg");
	this.shape_13.setTransform(-67.9,0.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_14.setTransform(-80.1,0.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgWBfQgGgCAAgGQAAgEAFgDIAHgDQACgCABgIIABgbIAAgUIAAgYIAAgLQAAghgBgJQgBgKgDgCIgIgCQgIgDAAgEQgBgEADgCQACgCAKgDIASgFIANgCQADAAACACQACADAAAGIAAAKQgCAvAAAvIABAtQAAAKADACIAIAEQAFADAAAFQABAFgHACQgHACgRAAQgTAAgHgCg");
	this.shape_15.setTransform(-87.6,0);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgvAyQgTgUAAgdQAAgdAUgUQATgUAdAAQAdAAASATQASASAAAdQAAAegTAUQgUAVgcAAQgcAAgTgTgAgYgnQgIALAAASQAAAZALASQALARAPAAQANAAAIgLQAIgKAAgSQAAgZgLgSQgMgRgOAAQgNAAgIAKg");
	this.shape_16.setTransform(-98.6,3.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AAdBdQgHgDAAgFQAAgGAJgDIAFgCQADgCABgIIAAggIAAgSIgBgFQgBgDgHgBQgGgBgZAAIgbABQgIABgCACIgBAEIgBAJIAAALIABAgQABAIACACIAGACQAIADAAAGQAAAFgHADQgIACgVAAQgUAAgIgCQgHgDAAgFQAAgGAIgDIAGgCQADgCABgRIABg4IgBgxQgBgUgCgCQgBgDgHgCQgHgDAAgGQAAgFAGgCQAGgCAYAAQAXAAAGACQAGACAAAFQAAAGgIADIgGADQgCACgBAIIgBAnQAAAFAFACQAFACATAAIAKAAIAcAAQAIgBADgDIABgCIAAgFIAAgGIAAghQgBgGgDgCIgFgDQgJgDAAgGQAAgFAGgCQAHgCAXAAQAYAAAFACQAGACAAAFQAAAGgIADIgGADQgDACgBASQgBARAAAkIABAyQABAVACACQABACAHADQAHACAAAGQAAAFgHADQgIACgUAAQgVAAgIgCg");
	this.shape_17.setTransform(-116,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayhosting, new cjs.Rectangle(-127.9,-17.7,256,35.5), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("Eg3igGjMBvFAAAIAANHMhvFAAAg");
	this.shape.setTransform(0,0,1.023,1.06);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-364.5,-45.5,729,91), null);


(lib.getpartystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgkAsIgEgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhPQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAhAAIAIABIAJACQAJADAGAGQAHAGADAIIADAJIABAIQAAAKgEAIIgEAHIgGAHIgHAFIgIAEQgJADgIAAgAgXgaQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAIAAAwQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIADABIAQAAQAFAAAGgCQAFgDAFgDQAEgDACgGQADgFAAgHQAAgFgDgGQgCgFgEgEQgFgDgFgCQgGgCgFgBIgQAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAg");
	this.shape.setTransform(77.1,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgdAsIgDgBIgCgCIAAhRQABAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACgBIA9AAIADACIABACIAAAEIAAACIgBADIgDACIgtAAIgCACIgBADIAAALIABAEIADABIAdAAIACABIABACIAAAEIAAACQAAAEgDAAIgdAAIgCACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAsAAQADABAAADIABAEIgBADIgBADIgCABg");
	this.shape_1.setTransform(67.8,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_2.setTransform(59.5,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAWAtIgCgBIgCgBIgBgBIgPgXIgCgDIgEgBIgLAAIgDABIgBADIAAAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgEABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAhQQAAgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAGACQAFADAFADQAEAEACAGQACAFAAAHQAAAIgCAEQgDAEgDADIgHAFQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIAAACIAEAFIAFAHIAFAHIACAFIgBACIgDACIgDABIgDABgAgRgbQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAAAAAABQAAAAABABQAAAAABABIADAAIASAAIAGAAIAGgDQACgBABgDQACgDgBgEQAAgHgEgEIgGgCIgGgBIgSAAIgDABg");
	this.shape_3.setTransform(51.7,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_4.setTransform(42.5,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_5.setTransform(34.6,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgTAqQgKgDgHgHIgBgCIAAgBIABgDIADgDIADgCIADgBIAEABIAGAEIAHAEQAEABAGAAIAGAAIAHgCIAFgEQACgDAAgEQAAgDgCgCQgDgDgDgBIgKgBIgJgCIgKgCQgFgBgEgCQgEgDgDgEQgCgFAAgGQAAgHADgFQAEgFAFgEQAFgDAHgBIALgCIAJABIAIACIAJADIAHAFIAAACIABABIgBADIgDADIgDACIgEABIgCAAQgFgEgFgDQgFgCgGAAIgGAAIgGACIgEAEQgCACAAAEQAAAFAEACIAKADIANACQAHABAHACQAGADAEADQAFAFAAAJQgBAIgDAGQgEAFgFAEQgGADgHACIgMACQgKAAgJgEg");
	this.shape_6.setTransform(26.7,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AAAAuIgDAAIgCAAIgCgCIAAgCIAAgeIgBgGIgCgEIgZgnIAAgBIABgCIACgCIAEgCIADgBIACABIACACIASAdIACABIABAAIACAAIACgBIARgdIACgCIAEgBIACAAIADACIAEACIABACIAAABIgBABIgZAnIgCAFIgBADIAAABIAAAfQgCADgCABg");
	this.shape_7.setTransform(14.7,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_8.setTransform(7.1,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAWAtIgCgBIgBgBIgCgBIgPgXIgCgDIgEgBIgLAAIgDABIgCADIABAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgDABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAhQQAAgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAGACQAFADAFADQAEAEACAGQACAFABAHQAAAIgEAEQgCAEgDADIgHAFQAAAAgBABQAAAAgBAAQAAABAAAAQAAABAAAAIAAACIADAFIAFAHIAFAHIACAFIgBACIgDACIgDABIgDABgAgRgbQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAAUQAAAAABABQAAAAAAABQAAAAABABQAAAAABABIADAAIASAAIAHAAIAEgDQADgBABgDQABgDABgEQAAgHgGgEIgEgCIgHgBIgSAAIgDABg");
	this.shape_9.setTransform(-0.7,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_10.setTransform(-9.9,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgeAtQgEAAgCgEIAAhSIACgCIACgBIAmAAQAGAAAFACQAGACAEAEQAFADACAFQADAFAAAHIgBAEIgBAEQgDAIgGAEQgGAEgHABQgHABgHAAIgPAAIgBAAIgBABIgCADIAAAcIgCACIgCAAIgDABgAgSgbQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAOIACADIACABIAWAAIAFgBIAEgCQADgBABgDIABgFIgBgFIgDgDIgFgDIgEAAIgWAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_11.setTransform(-18,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIABACIAAAEIAAACIgBADIgCACIguAAIgCACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAtAAQACABAAADIABAEIgBADIgBADIgCABg");
	this.shape_12.setTransform(-30.5,-0.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AAbAtIgEAAIgDgCIAAggQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgcAAQgBAAAAAAQgBAAgBABQAAAAAAAAQgBABAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAeQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCAAIgEAAIgDAAIgDgBIgCgCIAAhTIACgCIADgBIADAAIADAAQAEAAABADIAAAcIABAEIADABIAeAAIAEgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgcQACgDADAAIAFAAIAEABIACACIAABTQgBADgDAAg");
	this.shape_13.setTransform(-39.9,-0.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_14.setTransform(-48.4,-0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_15.setTransform(-59.4,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIAAACIAAAEIAAACIAAADIgCACIgtAAIgDACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAtAAQACABAAADIAAAEIAAADIgBADIgCABg");
	this.shape_16.setTransform(-66.9,-0.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgHAtIgIgDIgIgDIgIgGIgFgHIgFgHQgDgJAAgKIAAgIIADgJQAEgJAGgGIAIgFIAIgEIAIgDIAJgBQAFAAAFACIAKACQAJAFAHAHIAAACIgBADIgDADIgDACIgDACIgEgCIgFgEIgHgFQgEgCgGAAQgFABgGACQgFACgEAEQgFAFgCAFQgCAGAAAFQAAAGACAGQACAFAFAEQAEAEAFADQAGACAFABIAGgBIAGgBIAGgEQACgBACgDIAAgBIgBgDIgDgBIgQAAIgCgBIgBgDIAAgDIAAgDIAAgDQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAlAAIABABIABABQACADAAAFIAAADIgBAEIgHAMQgEAFgGAEQgFADgHACQgGACgHAAIgJgBg");
	this.shape_17.setTransform(-76.9,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getpartystarted, new cjs.Rectangle(-83.9,-8.4,167.9,16.9), null);


(lib.getinspired = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQA3QgGgDgFgFQgFgFgCgHQgDgHAAgIQAAgIADgHQACgFAFgGQAFgFAGgCQAHgDAIAAQAIAAAGADQAGAEAEAFIAAg1IAPAAIAABxIgOAAIAAgMQgEAHgHADQgHAEgHAAQgIAAgHgDgAgJgDQgEADgDACQgDAEgCAEQgBAFAAAFIABAKQACAEADAEQADAEAEACQAFACAEAAQAGAAAEgCQAFgCADgEQADgDACgFQABgFAAgFIgBgKIgFgIQgDgCgFgDQgEgCgGAAQgEAAgFACg");
	this.shape.setTransform(35.5,-0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMAjQgHgDgFgFQgFgEgDgIQgCgGAAgJQAAgHACgHQADgHAFgFQAFgFAGgCQAIgDAGgBQAIAAAGADQAHACAEAGQAEAEADAHQADAHAAAIIAAACIAAACIg4AAQAAAFACADIAFAIQADADAFABQADACAEAAQAHAAAFgEQAGgDACgEIAKAIQgFAIgIADIgIADIgJABQgHgBgHgCgAAVgFIgBgIQgCgEgCgDQgCgDgEgBQgEgBgFAAIgHABQgEABgDADQgDADgCAEQgCAEAAAEIApAAIAAAAg");
	this.shape_1.setTransform(26.8,1.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgTAlIAAg4IAAgGIgBgIIAOAAIAAAFIAAAGIABAAQADgGAEgDIAHgDIAGgCIAGABIgBANIgGAAQgFgBgEACQgEACgBAEQgDACgBAEQgBAFAAAEIAAAlg");
	this.shape_2.setTransform(20.3,1.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGA1IAAhGIANAAIAABGgAgGglQgDgCABgEQgBgDADgDQADgDADAAQAEAAADADQADADAAADQAAAEgDACQgDADgEAAQgDAAgDgDg");
	this.shape_3.setTransform(15.2,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglA3IAAhqIAOAAIAAALIABAAQADgGAHgEQAGgEAIAAQAIABAHADQAGACAFAFQAFAGACAGQADAHAAAIQAAAIgDAGQgCAGgFAGQgFAEgGADQgHAEgIAAQgHgBgGgDQgHgDgEgGIgBAAIAAAvgAgJgoQgFADgDADIgFAIIgBAKQAAAFABAFQACAFADACQADADAFACQAEACAFAAQAFAAAFgCQAEgCADgDQADgDACgEIABgKIgBgKQgCgEgDgEQgDgDgEgDQgFgCgFAAQgFAAgEACg");
	this.shape_4.setTransform(8.7,3.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPAiQgIgDgEgHIAKgIQACAEAGADQAEADAGAAIAEgBIAFgBIADgDIABgGQABgEgFgCQgFgDgIgCIgHgCQgEgBgDgCQgDgCgCgDQgCgEAAgFQAAgFACgEQADgFADgDIAJgDIAJgCQAIABAHADQAHADAEAFIgKAJQgDgEgEgDQgEgCgGAAIgEAAIgEACIgCACIgBAFQAAAFADABIALAFIAKACQAEACADACQAEACACADQABAEAAAEQAAAHgCAEQgDAEgDADQgFADgEABQgFABgGABQgHAAgIgEg");
	this.shape_5.setTransform(0.3,1.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AASAlIAAgnIgBgIIgCgHIgFgFQgEgCgEABQgIAAgFAFQgGAHAAAKIAAAmIgNAAIAAg4IAAgGIgBgIIANAAIABAFIAAAGIAAAAIAEgFIAFgEIAHgDIAGgCQAIABAEACQAGACACAEQAEAEACAFQABAFAAAHIAAArg");
	this.shape_6.setTransform(-7.3,1.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGA1IAAhGIANAAIAABGgAgGglQgDgCABgEQgBgDADgDQADgDADAAQADAAAEADQACADAAADQAAAEgCACQgEADgDAAQgDAAgDgDg");
	this.shape_7.setTransform(-13.5,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDApQgGgGAAgLIAAglIgNAAIAAgMIANAAIAAgUIANAAIAAAUIATAAIAAAMIgTAAIAAAkQAAAGADADQACADAFAAIAFgBIAEgBIAAAMIgGABIgGAAQgKAAgEgFg");
	this.shape_8.setTransform(-21.8,0.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMAjQgHgDgFgFQgFgEgDgIQgDgGAAgJQAAgHADgHQADgHAFgFQAFgFAGgCQAIgDAGgBQAIAAAHADQAGACAEAGQAFAEACAHQACAHABAIIAAACIAAACIg4AAQAAAFACADIAFAIQADADAEABQAFACADAAQAHAAAGgEQAEgDADgEIALAIQgGAIgIADIgIADIgJABQgHgBgHgCgAAVgFIgBgIQgCgEgCgDQgCgDgEgBQgEgBgFAAIgIABQgDABgDADQgDADgCAEQgCAEAAAEIApAAIAAAAg");
	this.shape_9.setTransform(-28.4,1.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgNA0QgLgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHIAIgHIAKgFQAKgEALAAIAMABIALADQAKAEAHAGIgLALQgFgFgHgDIgIgDIgJgBQgIAAgHAEQgIADgFAGQgFAGgDAIQgDAHAAAIQAAAJADAIQADAHAFAGQAFAGAIADQAHAEAJAAQAHAAAHgCIALgEIAAgdIgYAAIAAgMIAmAAIAAAzQgIAEgKADIgWACQgLAAgKgEg");
	this.shape_10.setTransform(-38.8,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getinspired, new cjs.Rectangle(-46.3,-11.2,89.1,22.4), null);


(lib.fourteentopright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteencookietopright();
	this.instance.parent = this;
	this.instance.setTransform(-82.5,-44);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentopright, new cjs.Rectangle(-82.5,-44,165,88), null);


(lib.fourteentopleft_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentopleft();
	this.instance.parent = this;
	this.instance.setTransform(-35,-11);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentopleft_1, new cjs.Rectangle(-35,-11,70,22), null);


(lib.fourteentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentable();
	this.instance.parent = this;
	this.instance.setTransform(-364,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentable_1, new cjs.Rectangle(-364,-45,728,90), null);


(lib.fourteenbottomright_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteenbottomright();
	this.instance.parent = this;
	this.instance.setTransform(-79.5,-34.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenbottomright_1, new cjs.Rectangle(-79.5,-34.5,158,69), null);


(lib.fourteenbottomleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteencookieleft();
	this.instance.parent = this;
	this.instance.setTransform(-42,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenbottomleft, new cjs.Rectangle(-42,-17.5,84,35), null);


(lib.ctarectanglevideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnaCbQhBAAgtgtQgtgtAAhBIAAAAQAAhAAtgtQAtgtBBAAIO1AAQBBAAAtAtQAtAtAABAIAAAAQAABBgtAtQgtAthBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectanglevideo, new cjs.Rectangle(-63,-15.5,126.1,31.1), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnaCbQhBAAgtgtQgtgtAAhBIAAAAQAAhAAtgtQAtgtBBAAIO1AAQBBAAAtAtQAtAtAABAIAAAAQAABBgtAtQgtAthBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-63,-15.5,126.1,31.1), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.fourteenctarollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_1 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(10).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer_1
	this.instance = new lib.ctarectanglevideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63,-15.5,126.1,31.1);


// stage content:
(lib.leaderboardfourteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_45 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_234 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(45).call(this.frame_45).wait(189).call(this.frame_234).wait(5));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(365.8,47.1,3.544,0.143,0,0,0,0.3,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(239));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(239));

	// fade-from-black
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(366.7,50.5,4.456,0.171,0,0,0,0.6,0.6);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.2,regY:0.7,scaleY:0.16,x:364.9,y:47,alpha:0},9).wait(230));

	// kale-logo
	this.instance_2 = new lib.kalelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(652.6,44.5);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.09,scaleY:0.09},0).to({scaleX:1.13,scaleY:1.13,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(217));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask.setTransform(240.6,53);

	// get-party-started
	this.instance_3 = new lib.getpartystarted();
	this.instance_3.parent = this;
	this.instance_3.setTransform(104,12.6);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(213).to({x:-216},0).to({x:124,alpha:1},10,cjs.Ease.get(1)).to({x:105.5},8,cjs.Ease.get(1)).wait(8));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask_1.setTransform(240.6,53);

	// holiday-tips-recipes-more
	this.instance_4 = new lib.holidaytipsrecipes();
	this.instance_4.parent = this;
	this.instance_4.setTransform(176.4,34.5);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(213).to({x:-143.6},0).to({x:196.4,alpha:1},10,cjs.Ease.get(1)).to({x:177.9},8,cjs.Ease.get(1)).wait(8));

	// sweet-inspiration
	this.instance_5 = new lib.sweetinspiration();
	this.instance_5.parent = this;
	this.instance_5.setTransform(129.6,27.4);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(153).to({alpha:1},10).wait(40).to({alpha:0},5).wait(31));

	// holiday-hosting
	this.instance_6 = new lib.holidayhosting();
	this.instance_6.parent = this;
	this.instance_6.setTransform(149.5,27.4);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(103).to({alpha:1},10).wait(40).to({alpha:0},5).wait(81));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask_2.setTransform(240.6,53);

	// party-ready-recipes
	this.instance_7 = new lib.partyreadyrecipesuse();
	this.instance_7.parent = this;
	this.instance_7.setTransform(148.5,27.4);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(45).to({x:-101.5,alpha:1},0).to({x:158.5},10,cjs.Ease.get(1)).to({x:148.5},8,cjs.Ease.get(1)).wait(40).to({alpha:0},5).wait(131));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("EggvASmMAAAglLMBGVAAAMAAAAlLg");
	mask_3.setTransform(240.6,53);

	// get-inspired
	this.instance_8 = new lib.getinspired();
	this.instance_8.parent = this;
	this.instance_8.setTransform(82.9,65.2);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(55).to({x:-58.1},0).to({x:87.9,alpha:1},10,cjs.Ease.get(1)).to({x:82.9},8,cjs.Ease.get(1)).wait(166));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask_4.setTransform(240.6,53);

	// cta-rollover
	this.cta_rollover = new lib.fourteenctarollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(83,66.3);
	this.cta_rollover.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(55).to({x:-57},0).to({x:88,alpha:1},10,cjs.Ease.get(1)).to({x:83},8,cjs.Ease.get(1)).wait(166));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask_5.setTransform(240.6,53);

	// cta-rectangle
	this.instance_9 = new lib.ctarectangle();
	this.instance_9.parent = this;
	this.instance_9.setTransform(83,66.3);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(55).to({x:-57},0).to({x:88,alpha:1},10,cjs.Ease.get(1)).to({x:83},8,cjs.Ease.get(1)).wait(166));

	// bottom-right
	this.instance_10 = new lib.fourteenbottomright_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(396.5,55.5);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(27).to({alpha:1},10).wait(202));

	// top-left
	this.instance_11 = new lib.fourteentopleft_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(280,11);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(22).to({alpha:1},10).wait(207));

	// cookie-top-right
	this.instance_12 = new lib.fourteentopright();
	this.instance_12.parent = this;
	this.instance_12.setTransform(552.6,44);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(32).to({alpha:1},10).wait(197));

	// cookie-bottom-left
	this.instance_13 = new lib.fourteenbottomleft();
	this.instance_13.parent = this;
	this.instance_13.setTransform(190,72.5);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(17).to({alpha:1},10).wait(212));

	// table
	this.instance_14 = new lib.fourteentable_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(239));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(362.2,32.1,731.8,114.8);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;